version: '3.9'

services:
  db:
    image: postgres:18
    container_name: ocufiiapi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salman
      POSTGRES_DB: ocufii
    ports:
      - "5432:5432"    # Expose DB to server for pgAdmin
    volumes:
      - pg_test_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  api:
    image: imsalmandev/ocufiiapi:latest
    container_name: ocufiiapi-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: TestDevWeb
      ConnectionStrings__OcufiiConnection: "Host=db;Database=ocufii;Username=postgres;Password=salman;Port=5432;"
    ports:
      - "8080:80"   # API will be available on http://<server-ip>:8080
    restart: unless-stopped

volumes:
  pg_test_data:
