// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OcufiiAPI.Data;

#nullable disable

namespace OcufiiAPI.Migrations
{
    [DbContext(typeof(OcufiiDbContext))]
    [Migration("20251118091101_FixRefreshTokenRelationship")]
    partial class FixRefreshTokenRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OcufiiAPI.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId", "Timestamp");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Beacon", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeaconMac")
                        .HasColumnType("text");

                    b.Property<string>("BeaconLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BeaconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BeaconType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationDetail")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "BeaconMac");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("OcufiiAPI.Models.BeaconData", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeaconMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Battery")
                        .HasColumnType("integer");

                    b.Property<string>("BeaconValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BeaconMac", "DateUpdated");

                    b.ToTable("BeaconData");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Billing", b =>
                {
                    b.Property<Guid>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvoicePeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvoicePeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BillingId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Configuration", b =>
                {
                    b.Property<string>("ConfigurationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConfigurationData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ConfigurationId", "ModeType");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("OcufiiAPI.Models.CustomerSupportTicket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerSupportTickets");
                });

            modelBuilder.Entity("OcufiiAPI.Models.DeviceToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceTokenValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MobileDevice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileOsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("OcufiiAPI.Models.EmailVerification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "Token");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("OcufiiAPI.Models.FeatureFlag", b =>
                {
                    b.Property<Guid>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FlagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FlagId");

                    b.HasIndex("TenantId");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Gateway", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayMac")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationDetail")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GatewayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSync")
                        .HasColumnType("boolean");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("WifiSettings")
                        .HasColumnType("jsonb");

                    b.HasKey("UserId", "GatewayMac");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("OcufiiAPI.Models.GatewayBeacon", b =>
                {
                    b.Property<Guid>("GatewayUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("BeaconUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeaconMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BeaconMac1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BeaconUserId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAssociated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayMac1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GatewayUserId1")
                        .HasColumnType("uuid");

                    b.HasKey("GatewayUserId", "GatewayMac", "BeaconUserId", "BeaconMac");

                    b.HasIndex("BeaconUserId1", "BeaconMac1");

                    b.HasIndex("GatewayUserId1", "GatewayMac1");

                    b.ToTable("GatewayBeacons");
                });

            modelBuilder.Entity("OcufiiAPI.Models.GatewayData", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("GatewayStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId", "GatewayMac", "DateUpdated");

                    b.ToTable("GatewayData");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Invite", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("InvitingUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("InviteId");

                    b.HasIndex("InvitingUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BillingId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Notification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotificationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Acknowledge")
                        .HasColumnType("boolean");

                    b.Property<int?>("Battery")
                        .HasColumnType("integer");

                    b.Property<string>("BeaconMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<bool?>("ContentAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("DataUuid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsSnoozed")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotificationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NotificationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecordTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sound")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId", "NotificationId", "NotificationTimestamp");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("OcufiiAPI.Models.PromoCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPromotional")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OsType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("PromoGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromoStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.HasIndex("PromoGroupId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("OcufiiAPI.Models.PromoGroup", b =>
                {
                    b.Property<Guid>("PromoGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfPromos")
                        .HasColumnType("integer");

                    b.Property<string>("PromoGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("PromoGroupId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PromoGroups");
                });

            modelBuilder.Entity("OcufiiAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OcufiiAPI.Models.ResellerDevice", b =>
                {
                    b.Property<Guid>("ResellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BeaconMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ResellerId", "Id");

                    b.ToTable("ResellerDevices");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RoleId"));

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission_level");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OcufiiAPI.Models.ScheduledReport", b =>
                {
                    b.Property<Guid>("ScheduledReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DateScheduled")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduledReportId", "ReportType");

                    b.ToTable("ScheduledReports");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Setting", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActiveShooter")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AutoLogout")
                        .HasColumnType("boolean");

                    b.Property<int?>("AutoLogoutInterval")
                        .HasColumnType("integer");

                    b.Property<bool?>("BypassFocus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Distress")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Emergency")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Emergency911")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MovementSound")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MovementVibration")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PersonalSafety")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalSafetyUserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Sound")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TermOfServiceTosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TosId")
                        .HasColumnType("uuid");

                    b.Property<string>("TosVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("TermOfServiceTosId");

                    b.HasIndex("UserId1");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("OcufiiAPI.Models.SnoozeSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeaconMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BeaconMac1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BeaconUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SnoozeDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SnoozeTimestampEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SnoozeTimestampStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BeaconMac");

                    b.HasIndex("BeaconUserId", "BeaconMac1");

                    b.ToTable("SnoozeSettings");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Subscription", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NoOfBeacons")
                        .HasColumnType("integer");

                    b.Property<int?>("NoOfGateways")
                        .HasColumnType("integer");

                    b.Property<string>("PlanId")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool?>("Sms")
                        .HasColumnType("boolean");

                    b.Property<string>("SubscriptionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Tenant", b =>
                {
                    b.Property<Guid>("ResellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomWorkflows")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ThemeConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ResellerId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("OcufiiAPI.Models.TermOfService", b =>
                {
                    b.Property<Guid>("TosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TermOfServiceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TosId");

                    b.HasIndex("CreatedByUserUserId");

                    b.ToTable("TermOfServices");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Thing", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Certificate")
                        .HasColumnType("text");

                    b.Property<string>("CertificateArn")
                        .HasColumnType("text");

                    b.Property<string>("CertificateId")
                        .HasColumnType("text");

                    b.Property<string>("GatewayMac1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GatewayUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.HasKey("UserId", "GatewayMac");

                    b.HasIndex("GatewayUserId", "GatewayMac1");

                    b.ToTable("Things");
                });

            modelBuilder.Entity("OcufiiAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccountHold")
                        .HasColumnType("boolean");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("GmtInfo")
                        .HasColumnType("text");

                    b.Property<string>("Imei")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedFromTwoStep")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubscriptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserGateway", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateAssociated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayMac1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GatewayUserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GatewayMac");

                    b.HasIndex("GatewayUserId", "GatewayMac1");

                    b.ToTable("UserGateways");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserNotify", b =>
                {
                    b.Property<Guid>("UserNotifyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("EnableLocation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableRecipient")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobileDevice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Otp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("ReceiveAlert")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SnoozeEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SnoozeStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserNotifyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifies");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserPurchase", b =>
                {
                    b.Property<string>("PurchaseToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OsType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PurchaseToken");

                    b.HasIndex("UserId");

                    b.ToTable("UserPurchases");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcknowledgementState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppAppleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("AutoRenewEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BundleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BundleVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CancelTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkedPurchaseToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NotificationSubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OriginalPurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OsType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubscriptionPlanType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubscriptionState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionUserId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("OcufiiAPI.Models.WeeklySystemActivityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WeeklySystemActivityReports");
                });

            modelBuilder.Entity("OcufiiAPI.Models.AuditLog", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Beacon", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Beacons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.BeaconData", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", null)
                        .WithMany("BeaconData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Beacon", "Beacon")
                        .WithMany("BeaconData")
                        .HasForeignKey("UserId", "BeaconMac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Billing", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Subscription", "Subscription")
                        .WithMany("Billings")
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("OcufiiAPI.Models.Tenant", "Tenant")
                        .WithMany("Billings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OcufiiAPI.Models.CustomerSupportTicket", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.DeviceToken", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.EmailVerification", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.FeatureFlag", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Tenant", "Tenant")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Gateway", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Gateways")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.GatewayBeacon", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Beacon", "Beacon")
                        .WithMany("GatewayBeacons")
                        .HasForeignKey("BeaconUserId1", "BeaconMac1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Gateway", "Gateway")
                        .WithMany("GatewayBeacons")
                        .HasForeignKey("GatewayUserId1", "GatewayMac1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcufiiAPI.Models.GatewayData", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", null)
                        .WithMany("GatewayData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Gateway", "Gateway")
                        .WithMany("GatewayData")
                        .HasForeignKey("UserId", "GatewayMac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Invite", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "InvitingUser")
                        .WithMany("SentInvites")
                        .HasForeignKey("InvitingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Role", "Role")
                        .WithMany("Invites")
                        .HasForeignKey("RoleId");

                    b.Navigation("InvitingUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Invoice", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Billing", "Billing")
                        .WithOne("Invoice")
                        .HasForeignKey("OcufiiAPI.Models.Invoice", "BillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Notification", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Permission", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OcufiiAPI.Models.PromoCode", b =>
                {
                    b.HasOne("OcufiiAPI.Models.PromoGroup", "PromoGroup")
                        .WithMany("PromoCodes")
                        .HasForeignKey("PromoGroupId");

                    b.HasOne("OcufiiAPI.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("PromoGroup");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("OcufiiAPI.Models.PromoGroup", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("OcufiiAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.ResellerDevice", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Setting", b =>
                {
                    b.HasOne("OcufiiAPI.Models.TermOfService", "TermOfService")
                        .WithMany("Settings")
                        .HasForeignKey("TermOfServiceTosId");

                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermOfService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.SnoozeSetting", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", null)
                        .WithMany("SnoozeSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Beacon", "Beacon")
                        .WithMany("SnoozeSettings")
                        .HasForeignKey("BeaconUserId", "BeaconMac1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("OcufiiAPI.Models.TermOfService", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Thing", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", null)
                        .WithMany("Things")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Gateway", "Gateway")
                        .WithMany("Things")
                        .HasForeignKey("GatewayUserId", "GatewayMac1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcufiiAPI.Models.User", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserGateway", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("UserGateways")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.Gateway", "Gateway")
                        .WithMany("UserGateways")
                        .HasForeignKey("GatewayUserId", "GatewayMac1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserNotify", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("UserNotifies")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserPurchase", b =>
                {
                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.UserSubscription", b =>
                {
                    b.HasOne("OcufiiAPI.Models.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcufiiAPI.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Beacon", b =>
                {
                    b.Navigation("BeaconData");

                    b.Navigation("GatewayBeacons");

                    b.Navigation("SnoozeSettings");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Billing", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Gateway", b =>
                {
                    b.Navigation("GatewayBeacons");

                    b.Navigation("GatewayData");

                    b.Navigation("Things");

                    b.Navigation("UserGateways");
                });

            modelBuilder.Entity("OcufiiAPI.Models.PromoGroup", b =>
                {
                    b.Navigation("PromoCodes");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Role", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Subscription", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("OcufiiAPI.Models.Tenant", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OcufiiAPI.Models.TermOfService", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("OcufiiAPI.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BeaconData");

                    b.Navigation("Beacons");

                    b.Navigation("DeviceTokens");

                    b.Navigation("EmailVerifications");

                    b.Navigation("GatewayData");

                    b.Navigation("Gateways");

                    b.Navigation("Notifications");

                    b.Navigation("Purchases");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentInvites");

                    b.Navigation("Settings");

                    b.Navigation("SnoozeSettings");

                    b.Navigation("Subscriptions");

                    b.Navigation("SupportTickets");

                    b.Navigation("Things");

                    b.Navigation("UserGateways");

                    b.Navigation("UserNotifies");
                });
#pragma warning restore 612, 618
        }
    }
}
